Controllers/QuizWizeQuestionsController.cs
using System.Data.SqlClient;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using QuizManagementSystem.Models;
using OfficeOpenXml;

namespace QuizManagementSystem.Controllers
{
    [CheckAccess]
    public class QuizWizeQuestionsController : Controller
    {
        private IConfiguration configuration;

        public QuizWizeQuestionsController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }

        
        public IActionResult QuizWizeQuestionsAdd(int? QuizWiseQuestionsID)
        {
            UserDropDown();
            QuizDropDown();
            QuestionDropDown();
            if (QuizWiseQuestionsID == null)
            {
                var m = new QuizWizeQuestionsModel
                {
                    CreationDate = DateTime.Now
                };
                return View(m);
            }

            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_MST_QuizWiseQuestions_SelectByID";
            command.Parameters.AddWithValue("@QuizWiseQuestionsID", QuizWiseQuestionsID);
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            QuizWizeQuestionsModel model = new QuizWizeQuestionsModel();

            foreach (DataRow dataRow in table.Rows)
            {
                model.QuizID = Convert.ToInt32(dataRow["QuizID"]);
                model.QuestionID = Convert.ToInt32(dataRow["QuestionID"]);
                model.UserID = Convert.ToInt32(dataRow["UserID"]);
            }
            return View(model);
        }

        public IActionResult Save(QuizWizeQuestionsModel model)
        {
            UserDropDown();
            QuizDropDown();
            QuestionDropDown();
            if (!ModelState.IsValid)
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;

                if (model.QuizWiseQuestionsID == 0)
                {
                    command.CommandText = "PR_MST_QuizWiseQuestions_Insert";
                    TempData["SuccessMessage"] = "QuizWiseQuestions Added successfully!";
                }
                else
                {
                    command.CommandText = "PR_MST_QuizWiseQuestions_Update";
                    TempData["SuccessMessage"] = "Data Updated successfully!";
                    command.Parameters.Add("@QuizWiseQuestionsID", SqlDbType.Int).Value = model.QuizWiseQuestionsID;
                }

                command.Parameters.Add("@QuizID", SqlDbType.Int).Value = model.QuizID;
                command.Parameters.Add("@QuestionID", SqlDbType.Int).Value = model.QuestionID;
                command.Parameters.Add("@UserID", SqlDbType.Int).Value = model.UserID;
                command.ExecuteNonQuery();
                return RedirectToAction("QuizWizeQuestionsList");
            }
            UserDropDown();
            return View("QuizWizeQuestionsAdd", model);
        }

       
        public IActionResult QuizWizeQuestionsList()
        {
            DataTable table = new DataTable();
            string connectionString = configuration.GetConnectionString("ConnectionString");

            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand("PR_MST_QuizWiseQuestions_SelectAll", connection))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            if (reader.HasRows)
                            {
                                table.Load(reader);
                                Console.WriteLine("Rows fetched: " + table.Rows.Count);
                            }
                            else
                            {
                                Console.WriteLine("No rows fetched from DB.");
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Database error: " + ex.Message);
                TempData["ErrorMessage"] = "Database error: " + ex.Message;
            }

            return View(table);
        }


        //[HttpPost]
        //public IActionResult QuizWizeQuestionsDelete(int QuizWiseQuestionsID)
        //{
        //    try
        //    {
        //        if (QuizWiseQuestionsID <= 0)
        //        {
        //            TempData["ErrorMessage"] = "Invalid ID";
        //            return RedirectToAction("QuizWizeQuestionsList");
        //        }

        //        string connectionString = configuration.GetConnectionString("ConnectionString");
        //        using (SqlConnection connection = new SqlConnection(connectionString))
        //        {
        //            connection.Open();
        //            using (SqlCommand command = new SqlCommand("PR_MST_QuizWiseQuestions_Delete", connection))
        //            {
        //                command.CommandType = CommandType.StoredProcedure;
        //                command.Parameters.Add("@QuizWiseQuestionsID", SqlDbType.Int).Value = QuizWiseQuestionsID;
        //                int rowsAffected = command.ExecuteNonQuery();

        //                if (rowsAffected == 0)
        //                    TempData["ErrorMessage"] = "No record found to delete.";
        //            }
        //        }

        //        TempData["SuccessMessage"] = "QuizWizeQuestion deleted successfully.";
        //    }
        //    catch (Exception ex)
        //    {
        //        TempData["ErrorMessage"] = "An error occurred: " + ex.Message;
        //    }
        //    return RedirectToAction("QuizWizeQuestionsList");
        //}

        public IActionResult QuizWizeQuestionsDelete(int QuizWiseQuestionsID)
        {
            try
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = connection.CreateCommand();
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "PR_MST_QuizWiseQuestions_Delete";
                    command.Parameters.Add("@QuizWiseQuestionsID", SqlDbType.Int).Value = QuizWiseQuestionsID;

                    command.ExecuteNonQuery();
                }

                TempData["SuccessMessage"] = "QuizWiseQuestion deleted successfully.";
                return RedirectToAction("QuizWizeQuestionsList");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occurred while deleting the QuizWiseQuestion: " + ex.Message;
                return RedirectToAction("QuizWizeQuestionsList");
            }
        }


        public void UserDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command2 = connection.CreateCommand();
            command2.CommandType = System.Data.CommandType.StoredProcedure;
            command2.CommandText = "PR_MST_User_DropdownForUser";
            SqlDataReader reader2 = command2.ExecuteReader();
            DataTable dataTable2 = new DataTable();
            dataTable2.Load(reader2);
            List<UserDropDownModel> userList = new List<UserDropDownModel>();
            foreach (DataRow data in dataTable2.Rows)
            {
                UserDropDownModel model = new UserDropDownModel();
                model.UserID = Convert.ToInt32(data["UserID"]);
                model.UserName = data["UserName"].ToString();
                userList.Add(model);
            }
            ViewBag.userList = userList;
        }

        public void QuizDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command2 = connection.CreateCommand();
            command2.CommandType = System.Data.CommandType.StoredProcedure;
            command2.CommandText = "PR_MST_Quiz_DropdownForQuiz";
            SqlDataReader reader2 = command2.ExecuteReader();
            DataTable dataTable2 = new DataTable();
            dataTable2.Load(reader2);
            List<QuizDropDownModel> quizList = new List<QuizDropDownModel>();
            foreach (DataRow data in dataTable2.Rows)
            {
                QuizDropDownModel model = new QuizDropDownModel();
                model.QuizID = Convert.ToInt32(data["QuizID"]);
                model.QuizName = data["QuizName"].ToString();
                quizList.Add(model);
            }
            ViewBag.quizList = quizList;
        }

        
        public void QuestionDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");

Views/QuizWizeQuestions/QuizWizeQuestionsAdd.cshtml
@model QuizWizeQuestionsModel
<main class="main" id="main">
    <div class="pagetitle">
        <h1>QuizWiseQuestions Add</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Dashboard</a></li>
                <li class="breadcrumb-item">Quiz Wise Questions</li>
                <li class="breadcrumb-item active">Add/Edit</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <!-- Vertical Form -->
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Quiz Wise Questions Add</h5>
            <form class="row g-3">
                <input asp-for="QuizWiseQuestionsID" type="hidden" />
                <div class="col-12">
                    <label for="inputQuizName" class="form-label"><span style="color:red">*</span>Quiz Name</label>
                    <select class="form-control" asp-for="QuizID" asp-items="@(new SelectList(ViewBag.quizList, "QuizID", "QuizName"))">
                        <option value="">Select Quiz</option>
                    </select>
                    <span asp-validation-for="QuizID" style="color:red"></span>
                </div>
                <div class="col-12">
                    <label for="inputQuestion" class="form-label"><span style="color:red">*</span>Question</label>
                    <select class="form-control" asp-for="QuestionID" asp-items="@(new SelectList(ViewBag.questionList, "QuestionID", "QuestionText"))">
                        <option value="">Select Question</option>
                    </select>
                    <span asp-validation-for="QuestionID" style="color:red"></span>
                </div>
                <div class="col-12">
                    <label for="inputUserName" class="form-label"><span style="color:red">*</span>User Name</label>
                    <select class="form-control" asp-for="UserID" asp-items="@(new SelectList(ViewBag.UserList, "UserID", "UserName"))">
                        <option value="">Select User</option>
                    </select>
                    <span asp-validation-for="UserID" style="color:red"></span>
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-success" asp-controller="QuizWizeQuestions" asp-action="Save">Save</button>
                    <button type="reset" class="btn btn-danger"><a asp-controller="QuizWizeQuestions" asp-action="QuizWizeQuestionsList" style="color:white;">Cancel</a></button>
                </div>

            </form><!-- Vertical Form -->
        </div>
    </div>
</main>

Views/QuizWizeQuestions/QuizWizeQuestionsList.cshtml
@model System.Data.DataTable
@using System.Data

<main id="main" class="main">

    <div class="pagetitle">
        <h1>QuizWizeQuestions List</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Dashboard</a></li>
                <li class="breadcrumb-item">QuizWizeQuestions</li>
                <li class="breadcrumb-item active">List</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

   
                <form>
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Search</h5>
                            <div class="row mb-1 mt-3">
                                <div class="col-sm-4">
                                    <label class="form-label" for="InputQuiz">Select Quiz</label>
                                    <input type="text" class="form-control" id="inputText" placeholder="Select Quiz">
                                </div>
                                <div>
                                    <button class="btn btn-success mt-3">Search</button>
                                    <button class="btn btn-danger mt-3">Reset</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>

    <span class="text-danger">@TempData["ErrorMessage"]</span>
    <span class="text-danger">@TempData["SuccessMessage"]</span>

    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">QuizWizeQuestions List</h5>
                        <div class="d-flex justify-content-end">
                            <a asp-controller="QuizWizeQuestions" asp-action="QuizWizeQuestionsAdd">
                                <button class="btn btn-primary mb-2">Add QuizWizeQuestions</button>
                            </a>
                            <a asp-controller="QuizWizeQuestions" asp-action="ExportToExcel">
                                <button class="btn btn-outline-success mb-2 ms-1">Export to Excel</button>
                            </a>
                        </div>


                        <!-- Table with stripped rows -->
                        <div class="table-responsive">
                        <table class="table datatable">
                            <thead>
                                <tr>
                                    <th>QuizWiseQuestionsID</th>
                                    <th>QuizName</th>
                                    <th>QuestionText</th>
                                    <th>UserName</th>
                                    <th data-type="date" data-format="YYYY/DD/MM">Created</th>
                                    <th data-type="date" data-format="YYYY/DD/MM">Modified</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (System.Data.DataRow row in Model.Rows)
                                {
                                    <tr>
                                        <td>@row["QuizWiseQuestionsID"]</td>
                                        <td>@row["QuizName"]</td>
                                        <td>@row["QuestionText"]</td>
                                        <td>@row["UserName"]</td>
                                        <td>@row["Created"]</td>
                                        <td>@row["Modified"]</td>
                                        <td>
                                            <a asp-controller="QuizWizeQuestions" asp-action="QuizWizeQuestionsAdd" asp-route-QuizWiseQuestionsID="@row["QuizWiseQuestionsID"]">
                                                <i class="bi bi-pencil-square" style="color:green"></i>
                                            </a>
                                            <a href="javascript:void(0);" onclick="confirmDelete('@row["QuizWiseQuestionsID"]')">
                                                <i class="bi bi-trash3 text-danger"></i>
                                            </a>

                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <!-- End Table with stripped rows -->

                        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
                            <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
                            <script>
                                function confirmDelete(quizwisequestionID) {
                                    Swal.fire({
                                        title: "Are you sure you want to delete?",
                                        text: "You won't be able to revert this!",
                                        icon: "warning",
                                        showCancelButton: true,
                                        confirmButtonColor: "#d33",
                                        cancelButtonColor: "#3085d6",
                                        confirmButtonText: "Yes, delete it!"
                                    }).then((result) => {
                                        if (result.isConfirmed) {
                                            window.location.href = "/QuizWizeQuestions/QuizWizeQuestionsDelete?QuizWiseQuestionsID=" + quizwisequestionID;
                                        }
                                    });
                                }
                            </script>

                       </div>
                    </div>
                </div>

            </div>
        </div>
    </section>

</main><!-- End #main -->